apiVersion: v1
kind: ConfigMap
metadata:
  name: face-detection-config
data:
  FLASK_ENV: "production"
  FLASK_APP: "app"
  MAIL_RELAY_HOST: "postfix-relay.mail.svc.cluster.local"
  MAIL_RELAY_PORT: "25"
