apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detection-app
  labels:
    app: face-detection
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: face-detection
  template:
    metadata:
      labels:
        app: face-detection
    spec:
      containers:
      - name: face-detection
        image: ghcr.io/kadam12g/face-detect-app/face-detect-app:4f7f50fb16a57bcfebaa648c8c574728f0296acb
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app"
        - name: SKYBIOMETRY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: skybiometry-api-key
        - name: SKYBIOMETRY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: skybiometry-api-secret
        - name: MAIL_RELAY_HOST
          value: "postfix-relay.mail.svc.cluster.local"
        - name: MAIL_RELAY_PORT
          value: "25"
        volumeMounts:
        - name: uploads
          mountPath: /app/app/static/uploads
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "200m"
            memory: "200Mi"
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
