apiVersion: apps/v1
kind: Deployment
metadata:
  name: face-detection-app
  labels:
    app: face-detection
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: face-detection
  template:
    metadata:
      labels:
        app: face-detection
    spec:
      initContainers:
      - name: volume-permissions
        image: ghcr.io/kadam12g/face-detect-app/face-detect-app:b38201df793947a654a4bbe59c4151697dea7ff1
        command: ["sh", "-c", "chown -R 1000:1000 /app/uploads && chmod -R 775 /app/uploads"]
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        securityContext:
          runAsUser: 0  # Run as root for permission changes
      - name: wait-for-postgres
        image: ghcr.io/kadam12g/face-detect-app/face-detect-app:b38201df793947a654a4bbe59c4151697dea7ff1
        command: ['sh', '-c', 
          'until nc -z -w5 postgres 5432; do echo waiting for postgres; sleep 2; done;']
      containers:
      - name: face-detection
        image: ghcr.io/kadam12g/face-detect-app/face-detect-app:b38201df793947a654a4bbe59c4151697dea7ff1
        ports:
        - containerPort: 5000
        env:
        - name: FLASK_APP
          value: "app"
        - name: SKYBIOMETRY_API_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: skybiometry-api-key
        - name: SKYBIOMETRY_API_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: skybiometry-api-secret
        - name: MAIL_RELAY_HOST
          value: "postfix-relay.mail.svc.cluster.local"
        - name: MAIL_RELAY_PORT
          value: "25"
        # PostgreSQL environment variables
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-user
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secrets
              key: postgres-password
        volumeMounts:
        - name: uploads
          mountPath: /app/app/static/uploads
        resources:
          limits:
            cpu: "1"
            memory: "500Mi"
          requests:
            cpu: "200m"
            memory: "200Mi"
        securityContext:
          runAsUser: 1000  # Match the UID of appuser in your container
          runAsNonRoot: true
          allowPrivilegeEscalation: false
      volumes:
      - name: uploads
        persistentVolumeClaim:
          claimName: uploads-pvc
