apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: face-detection-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "16m"
spec:
  tls:
  - hosts:
    - face-detection.kissadam.info
    secretName: face-detection-tls
  rules:
  - host: face-detection.kissadam.info
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: face-detection-service
            port:
              number: 80
