---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-secrets
  namespace: default
spec:
  encryptedData:
    postgres-password: AgBbFwCgLmBm6jzc5BC3aks2nFw58OfEiH3jRwV3ZkOoNN0kK6o1nPJCgXf1IDjzHlnXRd037DL+lqmUeHlcLJOn4XP5MCG1oCxeylr3X8Dk3Hbw+MlnY/U8GADntXDJJWHFncYkXM3CNIiYEXNH98hLbuvDcr/d4JxZlBnloaJVt/N5J08UxX85/f4qaOf4FF9ei9l/KoNQnFeFgLOgIMRU3gUohs1Lktt/3FJFEKN0NGDcsBuwsYDzHIZVJuZXqzfo7Ra+N0Dz8tAjRO7ah2CHXkIFI1E+lpRJ35G8QlF7ZcahsvSgkE2pcGj+yaU2o1AgSEUIK/zzv6ijaHYQegtSBgjKQeJj1585N2z9fDsAqV5pTKOU2zedd66U4RvdAlhKUHNkwJJTc1YUZQ7WH1ZW3XR3nfMJR0IxQpOL0ov7QVVf+niDc7i3v+P1ZRGwc79zX3IqXLf7f8pgpnAlhsxvxfX102t75PYVLAswpvVzmMJT5WHxGHW+5ROOwm3F/nYRLAVE/nXVwg1dqgSYZM8hzXsGITtQUwAxINP1qyOo6ExqEFpYPSnfXUBBF602vxbwUzlKcoNZfYDLkAkKcKSI/hnU8w/QNbf48FqFEhfjEQSgFaNVLNt6AsIrj99k927wNSgXCe5d/gSnGyr6l3OhKcl/wF6N5osZV1J6INALHKAaYLG2GqU5ql7DTa87aimcEgY1UQ8PVZ442Jv8JwBa
    postgres-user: AgCgF1xanhqbQQw6DLekrvhz6aREKFl0HTSYfazzcB+sVULX71pJw6RhWjIpD5sWp93fjPSGRLNI7JtxvIsPVwzqv/IOHV/VcCs9RqXIwoqBKe6pyca2MtwScXj0G5sa1Zg2msgjhDaSx9wcyOweUz3Are/aNrhHhy5kN4Sktk4uqAxyeuj/X09qN+C3WxRuiqZiwmmSrN7D8ZDM4zh8NynLfufC4vcE7AfQ0ftXijWLI5D12KDY/AmD7lMh2rPCFr8yDBjhqJbotfGF6tEAMgccUJWRQ19fNGBr/mRCxsprPHtc9vCYXmnkJalsqH7wRttpeHvng0Rlh0t2e+sLBCKH2Cop8iXI2OSYzuuOvMI8SKMzcb+aFjBacP2EsrP0g/oOurosDuWLSRBN5kHc/jvX8mGa5JdKA6BGFKX02vWs1UJ6CP3E57AqQP7uOU358pOHZNTYAS0MSYyhP2wTZ+3jKvxX1yXy2zlN6QvTsPQdgl0oUDRKOARW2xHo1wYvYshNkpt8WT8TWW/dCpXaH7FXhZyjeQufC5Rq6J1YZtFEMOkn2nHNXDeXyDDW0FvDYfT4ldlpqrq65z2aAx36rzrz9MyVCP6tn1wSh8xvmWNr/JcI36bCoGBTWWNrbWFIV2Xw+I8lezbn9n+/9g0cXQ327genye3bZf3SdMHsiIg/NEljHvDzwqzXfJGRH+/uibP1UZrt6YpFer+d
  template:
    metadata:
      creationTimestamp: null
      name: postgres-secrets
      namespace: default
    type: Opaque
