---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: demo-secret
  namespace: demo
spec:
  encryptedData:
    secret-key: AgBX+VQQNdEcXNCTKOpgz8ZIxuXd89I+0CycSsSEZoDpkSNaytVCR+Is/PP3ALqpYUp8ZKHJjNnVnwmMLlRAcXmj9eAYiDskgPlhF89nVHjvfXYGkfGU2XNU/EgypStK+kxITqr8c+cXLVHY/uUCoZ0xlRwMj9k9BmoPg63Rh2AgknhmWXL9BzgcnlG1Yo9oTDfVEl2KfJIk7IiWFfDqCenVvGFPq6xrHrg+GC5s1wNhHL9xe4Hd1gzna29DTb4N5gThgTq7a2HMeiuwYqg6E1ZMjj5Emsj/0+0w9sFh7mCUDqUFxxtt7EjC1scL5ce4EfNVGfG05eiU7a/TRLb69FV0QuLZwC5WrwBeyAEj6cPoUZ0HI4Hnaj2r41sOOc6jAsMCLNp9vmE0E1ZCjIoNAoBtP4/LyFqamWzVvKqdgB72oD4mZMXtatu7F5fHpBbyS5N/qEIQmUiOCg5egOvhFd9tqtujWYwvV66zcY6CkXPSLSOoa66KJXHJ53Yi5whWgD0je6TRhquiLpCM+9OUIrAWEWD0kz8TwHHF83gGAmaRf4aBvD16xjapesZ6bXcPdXYlsqZeLYGrfHnNeJTL7cXUtKbgoSvYLKy3dZdwTvW/p/I1/a/ESjN+cl2KjefoFbzTdOPMXaHr6bUdD0tiNZzdrCU2lLr8Zep0tnomjJrLxpkHvuurcHHVVg9m7gOJ9kW47aSAkg7Wr4pkZ0l++H+G816J8drw
  template:
    metadata:
      creationTimestamp: null
      name: demo-secret
      namespace: demo
    type: Opaque
